version: "3.1"

services:
  nginx:
    image: nginx:0.01
    build:
      context: ./requirements/nginx
    init: true
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - mynet

  wordpress:
    image: wordpress:0.01
    build:
      context: ./requirements/wordpress
    init: true
    container_name: wordpress
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - mynet

  mariadb:
    image: mariadb:0.01
    build:
      context: ./requirements/mariadb
    init: true
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/Users/youngwch/42/5circle/Inception/subject/srcs/data/mariadb"

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/Users/youngwch/42/5circle/Inception/subject/srcs/data/wordpress"